const fs=require('fs'),path=require('path');const {chromium}=require('C:/Users/j9010/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const root=path.resolve(__dirname,'..'),out=path.join(root,'research/native-settings-52');
function closing(s,start){let depth=0,quote=false,escape=false;for(let i=start;i<s.length;i++){let c=s[i];if(quote){if(escape)escape=false;else if(c==='\\')escape=true;else if(c==='"')quote=false;continue;}if(c==='"')quote=true;else if(c==='{')depth++;else if(c==='}'&&!--depth)return i;}throw Error('Unbalanced template');}
function parse(s){let nodes=[],own='',at=0;const re=/#([\w]+):(\w+)\s*\{/g;while(true){re.lastIndex=at;const m=re.exec(s);if(!m)break;own+=s.slice(at,m.index);const open=re.lastIndex-1,end=closing(s,open),body=s.slice(open+1,end);nodes.push({name:m[1],type:m[2],...parse(body)});at=end+1;}own+=s.slice(at);return{own,nodes};}
function prop(s,key){const m=[...s.matchAll(new RegExp('(?:^|[;\\s])'+key+':\\s*([^;]+);','g'))].pop();return m?m[1].trim():null;}
function color(s){if(!s)return null;return s.replace(/#([0-9a-f]{6})([0-9a-f]{2})/i,(_,rgb,a)=>'#'+rgb+a);}
function styles(n){let css='position:absolute;box-sizing:border-box;';for(const k of ['x','y','width','height','z']){const v=prop(n.own,k);if(v)css+=({x:'left',y:'top',z:'z-index'}[k]||k)+':'+v+';';}if(!prop(n.own,'width'))css+='width:100%;';if(!prop(n.own,'height'))css+='height:100%;';if(prop(n.own,'pivot_x'))css+='transform:translateX(-'+Number(prop(n.own,'pivot_x'))*100+'%);';const c=color(prop(n.own,'color'));if(n.type==='color')css+='background:'+(c||'transparent')+';';if(n.type==='color_icon_button'){const start=n.own.lastIndexOf('btn: {'),b=start<0?'':n.own.slice(start+6,closing(n.own,start+5));css+='background:'+(color(prop(b,'back_color'))||'transparent')+';border:'+(prop(b,'stroke')||1)+'px solid '+(color(prop(b,'color'))||'#4b4a49')+';';}if(n.type==='label')css+='display:flex;align-items:center;font-family:Segoe UI,Arial,sans-serif;font-weight:'+(n.own.includes('#bold_label')?'700':'400')+';font-size:'+(prop(n.own,'size')||16)+'px;color:'+(c||'#eee')+';white-space:nowrap;';if(prop(n.own,'align_x')==='Center')css+='justify-content:center;';if(prop(n.own,'rounding'))css+='border-radius:3px;';return css;}

const source=fs.readFileSync(path.join(out,'settings.ui'),'utf8');const definitions=JSON.parse(fs.readFileSync(path.join(out,'definitions.json')));
const titles=['Combat & casting','Keybinds','Camera','Interface'];
function doc(page){const tree=parse(source.slice(source.indexOf('{')+1,source.lastIndexOf('}')));const window=tree.nodes.find(n=>n.name==='window');let options=definitions.options.filter(d=>d.page===page);const find=name=>window.nodes.find(n=>n.name===name);const hide=name=>{find(name).own+=' visible: false;'};const set=(name,key,value)=>{find(name).own+=' '+key+': '+value+';';};const text=(name,t)=>set(name,'text',JSON.stringify(t));
for(let i=0;i<4;i++){find('nav'+i).own+=' btn: {back_color: '+(page===i?'#fdee00ff':'#1c1a18ff')+';stroke:0;}';text('nav_label'+i,i===0?'Combat &\ncasting':titles[i]);set('nav_label'+i,'color',page===i?'#1c1a18ff':'#cbc9c7ff');set('nav_icon'+i,'color',page===i?'#1c1a18ff':'#eeececff');}
text('page_title',titles[page]);text('page_hint',['Choose how movement, targeting and ability inputs behave.','Click a binding; Esc cancels capture, Backspace clears it.','Adjust how the camera follows and moves around the battlefield.','Cursor and battlefield feedback, alongside your existing HUD.'][page]);text('position',page===1?'1-6 / '+definitions.bindings.length:'0'+(page+1)+' / 04');
for(let i=0;i<6;i++){for(let j=0;j<2;j++){hide('choice'+i+'_'+j);hide('bind'+i+'_'+j);}hide('drop'+i);hide('slider'+i);hide('value'+i);const d=page===1?definitions.bindings[i]:options[i];if(!d){hide('row'+i);hide('label'+i);hide('hint'+i);continue;}text('label'+i,d.label);text('hint'+i,d.hint||d.group);if(page===1){for(let j=0;j<2;j++){set('bind'+i+'_'+j,'visible','true');find('bind'+i+'_'+j).own+=' text: {text: '+JSON.stringify(d.keys[j])+';size:18;}';}}else if(d.slider){const[lo,hi,step,unit]=d.slider;set('slider'+i,'visible','true');set('value'+i,'visible','true');text('value'+i,d.default+unit);const slider=find('slider'+i);slider.nodes.find(n=>n.name==='fill').own+=' width: '+(d.default-lo)/(hi-lo)*100+'%;';slider.nodes.find(n=>n.name==='thumb').own+=' x: '+Math.max(25,Math.min(247,(d.default-lo)/(hi-lo)*272))+'px;';}else if(d.choices.length===2){for(let j=0;j<2;j++){const n=find('choice'+i+'_'+j);n.own+=' visible: true; btn: {back_color: '+(j===d.default?'#eeececff':'#5b5b5bff')+';stroke:0;} text: {text: '+JSON.stringify(d.choices[j])+';size:18;color: '+(j===d.default?'#393939ff':'#b8b6b5ff')+';}';}}else{const n=find('drop'+i);n.own+=' visible: true; btn: {back_color:#eeececff;stroke:0;} text: {text: '+JSON.stringify(d.choices[d.default]+'   v')+';size:18;color:#393939ff;}';}}
if(page!==1){hide('up');hide('down');}if(page===3){set('cursor','visible','true');set('cursor','x','870px');set('cursor','y','247px');}for(let i=0;i<3;i++)hide('popup'+i);for(const n of ['conflict_title','conflict_text','replace','dismiss'])hide(n);
function render(n,parent=''){const id=parent?parent+'.'+n.name:n.name;let css=styles(n),content='';if(prop(n.own,'visible')==='false')css+='display:none;';if(n.type==='label'){const m=[...n.own.matchAll(/text:\s*("(?:\\.|[^"\\])*")/g)].pop();content=m?JSON.parse(m[1]):'';css+='white-space:pre-wrap;font-family:Native;';}if(n.type==='color_icon_button'){const m=[...n.own.matchAll(/text:\s*("(?:\\.|[^"\\])*")/g)].pop();content=m?JSON.parse(m[1]):'';const start=n.own.lastIndexOf('text: {');const t=start<0?'':n.own.slice(start+7,closing(n.own,start+6));css+='display:flex;align-items:center;justify-content:center;font-family:Native;font-weight:600;font-size:'+(prop(t,'size')||18)+'px;color:'+(color(prop(t,'color'))||'#eeecec')+';';if(n.name.startsWith('choice')||n.name.startsWith('drop'))css+='border-radius:25px;';}if(n.type==='image'){const src=prop(n.own,'source');if(src){const name=JSON.parse(src).split('/').pop();const file=path.join(root,'probe/ui',name+'.png');if(!fs.existsSync(file))throw Error('Missing '+file);content='<img src="data:image/png;base64,'+fs.readFileSync(file).toString('base64')+'"/>';}}if(prop(n.own,'visible')==='false')css+='display:none;';return '<div data-node="'+id+'" style="'+css+'">'+content+n.nodes.map(c=>render(c,id)).join('')+'</div>';}
const font=fs.readFileSync(path.join(root,'probe/font/manrope_medium.ttf')).toString('base64');return '<meta charset="utf-8"><style>@font-face{font-family:Native;src:url(data:font/ttf;base64,'+font+')}body{margin:0;background:#202928}img{width:100%;height:100%}</style>'+tree.nodes.map(n=>render(n)).join('');}
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1920,height:1080}});for(let i=0;i<4;i++){await page.setContent(doc(i));await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,'page-'+i+'.png')});const bad=await page.evaluate(()=>[...document.querySelectorAll('[data-node]')].filter(n=>n.offsetParent!==null).filter(n=>{const r=n.getBoundingClientRect();return r.x<0||r.y<0||r.right>1921||r.bottom>1081}).map(n=>n.dataset.node));if(bad.length)throw Error('Overflow '+bad);console.log(titles[i]+': template layout and asset paths checked');}await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
