// Offline layout check derived from the exported Rust native-UI templates.
// This approximates font/rendering behavior; it is not a native game test.
const fs=require('fs'),path=require('path');
const {chromium}=require('C:/Users/j9010/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'research/hud-layout-44');
const assets=JSON.parse(fs.readFileSync('C:/Users/j9010/.codex/visualizations/2026/09/30/01a0f24c-b767-73b0-b835-26937b07649e/hud-preview-assets.json','utf8'));
function closing(s,start){let depth=0,quote=false,escape=false;for(let i=start;i<s.length;i++){let c=s[i];if(quote){if(escape)escape=false;else if(c==='\\')escape=true;else if(c==='"')quote=false;continue;}if(c==='"')quote=true;else if(c==='{')depth++;else if(c==='}'&&!--depth)return i;}throw Error('Unbalanced template');}
function parse(s){let nodes=[],own='',at=0;const re=/#([\w]+):(\w+)\s*\{/g;while(true){re.lastIndex=at;const m=re.exec(s);if(!m)break;own+=s.slice(at,m.index);const open=re.lastIndex-1,end=closing(s,open),body=s.slice(open+1,end);nodes.push({name:m[1],type:m[2],...parse(body)});at=end+1;}own+=s.slice(at);return{own,nodes};}
function prop(s,key){const m=[...s.matchAll(new RegExp('(?:^|[;\\s])'+key+':\\s*([^;]+);','g'))].pop();return m?m[1].trim():null;}
function color(s){if(!s)return null;return s.replace(/#([0-9a-f]{6})([0-9a-f]{2})/i,(_,rgb,a)=>'#'+rgb+a);}
function styles(n){let css='position:absolute;box-sizing:border-box;';for(const k of ['x','y','width','height','z']){const v=prop(n.own,k);if(v)css+=({x:'left',y:'top',z:'z-index'}[k]||k)+':'+v+';';}if(!prop(n.own,'width'))css+='width:100%;';if(!prop(n.own,'height'))css+='height:100%;';if(prop(n.own,'pivot_x'))css+='transform:translateX(-'+Number(prop(n.own,'pivot_x'))*100+'%);';const c=color(prop(n.own,'color'));if(n.type==='color')css+='background:'+(c||'transparent')+';';if(n.type==='color_icon_button'){const start=n.own.lastIndexOf('btn: {'),b=start<0?'':n.own.slice(start+6,closing(n.own,start+5));css+='background:'+(color(prop(b,'back_color'))||'transparent')+';border:'+(prop(b,'stroke')||1)+'px solid '+(color(prop(b,'color'))||'#4b4a49')+';';}if(n.type==='label')css+='display:flex;align-items:center;font-family:Segoe UI,Arial,sans-serif;font-weight:'+(n.own.includes('#bold_label')?'700':'400')+';font-size:'+(prop(n.own,'size')||16)+'px;color:'+(c||'#eee')+';white-space:nowrap;';if(prop(n.own,'align_x')==='Center')css+='justify-content:center;';if(prop(n.own,'rounding'))css+='border-radius:3px;';return css;}
const text={kills:'18',deaths:'3',assists:'2',slash1:'/',slash2:'/',cs:'145',level:'12',hp_current:'1284',hp_max:' / 1904',gold:'860',purchase:'−240',respawn:'10'};
function render(n,parent='',state='alive'){const id=parent?parent+'.'+n.name:n.name;let css=styles(n),content='';let visible=prop(n.own,'visible')!=='false';
 if(['tooltip','feedback','death_banner'].includes(n.name))visible=false; if(n.name==='purchase_check')visible=false; 
 if(n.name==='hourglass'||n.name==='respawn')visible=state==='dead';
 if(['hp_current','hp_max'].includes(n.name)&&state==='dead')visible=false;
 if(id.startsWith('skill')&&(n.name==='icon')){const slot=+id.match(/^skill(\d)/)[1];visible=true;content='<img src="'+assets.skills.lancer[slot]+'"/>';}
 if(id.startsWith('skill')&&n.name==='shade')visible=state==='dead'||id.startsWith('skill1');
 if(id==='skill1.cooldown')content=state==='dead'?'--':'3.6s';
 if(id==='skill2')css+='background:#fdee00;';
 if(n.name==='lock'||n.name==='uses')visible=false;
 if(/^item[0-5]\.icon$/.test(id)){visible=true;content='<img src="'+assets.items[+id[4]%assets.items.length]+'"/>';}
 if(id==='next.icon'){visible=true;content='<img src="'+assets.items[2]+'"/>';}
 if(id==='health.fill')css+='width:'+(state==='dead'?0:67.44)+'%;';
 if(/^hp_tick\d+$/.test(id)){const i=+id.slice(7);visible=state!=='dead'&&(i+1)*100<1904;css+='left:'+(780+360*(i+1)*100/1904)+'px;';}
 if(id==='health.trail')css+='width:'+(state==='dead'?0:71.4)+'%;'; if(id==='next.progress.fill')css+='width:78%;';
 if(id==='menu.slider.fill')css+='width:'+(state==='menu24'?0:100)+'%;';
 if(state==='selection'&&n.name==='portrait'){visible=true;content='<img src="'+assets.portraits.lancer+'"/>';} if(n.type==='image'&&!content){const src=prop(n.own,'source');if(src){const glyph=JSON.parse(src).split('/').pop();const f=path.join(root,'probe/ui',glyph+'.png');if(fs.existsSync(f))content='<img src="data:image/png;base64,'+fs.readFileSync(f).toString('base64')+'"/>';}}
 if(n.type==='label'&&!content)content=text[n.name]||((prop(n.own,'text')||'""').replace(/^"|"$/g,''));
 if(state==='selection'&&parent===''&&!/^lane[0-4]$/.test(n.name)&&n.name!=='primary'&&n.name!=='strip'&&n.name!=='edge'&&!n.name.startsWith('corner'))visible=false; if(!visible)css+='display:none;';
 return '<div data-node="'+id+'" style="'+css+'">'+content+n.nodes.map(c=>render(c,id,state)).join('')+'</div>';}
function document(state){const source=fs.readFileSync(path.join(out,'player.ui'),'utf8');const start=source.indexOf('{');const tree=parse(source.slice(start+1,source.lastIndexOf('}')));let menu='';if(state==='selection'){const q=fs.readFileSync(path.join(out,'session.ui'),'utf8');const t=parse(q.slice(q.indexOf('{')+1,q.lastIndexOf('}'))); menu='<div style="position:absolute;left:732px;bottom:58px;width:456px;height:80px;z-index:1100">'+t.nodes.filter(n=>/^lane[0-4]$/.test(n.name)||n.name==='primary').map(n=>{if(n.name==='primary'){n.own=n.own.replace('width: 40px','width: 48px').replace('height: 40px','height: 48px');n.own+=' btn: { color: #fdee00ff; back_color: #fdee00ff; stroke: 1; }';}if(n.name==='lane2')n.own=n.own.replace('#4b4a49ff','#fdee00ff');return render(n,'',state);}).join('')+'</div>';} if(state.startsWith('menu')){const size=state==='menu24'?24:64,ratio=(size-24)/40;const s=fs.readFileSync(path.join(out,'session.ui'),'utf8');const m=parse(s.slice(s.indexOf('{')+1,s.lastIndexOf('}'))).nodes.find(n=>n.name==='menu');m.own=m.own.replace('visible: false','visible: true');const slider=m.nodes.find(n=>n.name==='slider');slider.nodes.find(n=>n.name==='fill').own+=' width: '+ratio*100+'%;';slider.nodes.find(n=>n.name==='handle').own=slider.nodes.find(n=>n.name==='handle').own.replace('x: 44px','x: '+Math.max(6,Math.min(214,ratio*220))+'px');m.nodes.find(n=>n.name==='size').own+=' text: "'+size+' px";';const preview=m.nodes.find(n=>n.name==='preview');preview.own=preview.own.replace('width: 32px','width: '+size+'px').replace('height: 32px','height: '+size+'px');menu='<div style="position:absolute;z-index:1100;left:16px;bottom:0;width:132px;height:50px">'+render(m,'',state)+'</div>';}
return '<!doctype html><meta charset="utf-8"><style>body{margin:0;background:#363636}img{width:100%;height:100%;image-rendering:pixelated}#hud{position:absolute;bottom:0;left:0;width:1920px;height:146px}</style><div id="hud">'+tree.nodes.map(n=>render(n,'',state)).join('')+'</div><div style="position:absolute;z-index:1100;left:16px;bottom:7px;display:flex;gap:4px">'+['hud_pause','camera','hud_more'].map(g=>'<img style="width:32px;height:36px;padding:4px;box-sizing:border-box" src="data:image/png;base64,'+fs.readFileSync(path.join(root,'probe/ui',g+'.png')).toString('base64')+'"/>').join('')+'</div>'+menu;}
(async()=>{const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});try{const page=await browser.newPage({viewport:{width:1920,height:330}});for(const state of ['alive','dead','menu24','menu64','selection']){const html=document(state);fs.writeFileSync(path.join(out,state+'.html'),html);await page.setContent(html);await page.screenshot({path:path.join(out,state+'.png')});const result=await page.evaluate(()=>[...document.querySelectorAll('[data-node]')].filter(e=>getComputedStyle(e).display!=='none'&&e.offsetParent!==null).filter(e=>{const r=e.getBoundingClientRect();return r.left<0||r.right>1920||r.bottom>330;}).map(e=>e.dataset.node));if(result.length)throw Error('Overflow: '+result);console.log(state+': layout rendered, no viewport overflow');}
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
